version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./src:/app/src
        ports:
            - '3100:3100'
        networks:
            - integration_default # For dev environment this will need to be changed
networks:
    integration_default:
        external: true
